version: '3.8'

services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: password

  tarantool:
    image: tarantool/tarantool

  tarantool-admin:
    image: quay.io/basis-company/tarantool-admin
    environment:
      TARANTOOL_CONNECTIONS: 'tarantool'
    ports:
      - "80:80"

  tests:
    build: .
    depends_on:
      - postgres
      - tarantool
    volumes:
      - './registry:/app/registry'
      - './tests:/app/tests'
